# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # - name: Install requirements.txt
      # run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: pip upgraden
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        sudo apt-get install build-essential nginx supervisor
        python -m pip install gunicorn gevent
        python -m pip install .

    - name: setup config file
      shell: bash
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        #PERMISSIONS: ${{secrets.XXX}}
      run: |
        cat <<EOF >> bepasty.conf

        SITENAME = 'bepasty.example.org'

        APP_BASE_PATH = None  # '/bepasty'

        UPLOAD_LOCKED = False

        ASCIINEMA_THEME = 'asciinema'

        MAX_ALLOWED_FILE_SIZE = 5 * 1000 * 1000 * 1000

        MAX_BODY_SIZE = 1 * 1024 * 1024 - 8192  # 8kiB safety margin, issue #155

        MAX_RENDER_SIZE = {
            'text/x-bepasty-list': 1000 * 38,
            'HIGHLIGHT_TYPES': 100 * 1000,
            'application/pdf': 10 * 1000 * 1000,
            'application/x-pdf': 10 * 1000 * 1000,
            'image/': 10 * 1000 * 1000,
            'audio/': 1 * 1000 * 1000 * 1000,
            'video/': 5 * 1000 * 1000 * 1000,
            '': 1 * 1000 * 1000,
        }
        USE_PYTHON_MAGIC = False
        STORAGE = 'filesystem'
        STORAGE_FILESYSTEM_DIRECTORY = '/tmp/'
        SECRET_KEY = '$SECRET_KEY'
        SESSION_COOKIE_SECURE = True
        PERMANENT_SESSION = False
        PERMANENT_SESSION_LIFETIME = 31 * 24 * 3600

        PERMISSIONS = {
        }

        DEFAULT_PERMISSIONS = ''
        EOF
    - name: Start bepasty server
      shell: bash
      run: BEPASTY_CONFIG=$(pwd)/bepasty.conf bepasty-server --debug &

  sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        python -m venv env/
        source env/bin/activate
        python -m pip install .
    - uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        virtual-environment: env/